# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RELEASE_VERSION
    type: string
    displayName: Version to release, e.g. 1.0.0
    default: 1.0.0-SNAPSHOT
  - name: NEXT_SNAPSHOT_VERSION
    type: string
    displayName: Next snapshot version, e.g. 1.0.1-SNAPSHOT
    default: 1.0.1-SNAPSHOT

variables:
  JDK_VERSION: 1.17
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTIONS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'
  MAVEN_COMMAND_LINE_ARGUMENTS: '--batch-mode'
  # TODO: RELEASE_BRANCH: main
  RELEASE_BRANCH: release-pipeline
  ${{ if eq(variables['Build.SourceBranchName'], 'release-pipeline') }}:
    IS_RELEASE: ${{ not(endsWith(parameters['RELEASE_VERSION'], 'SNAPSHOT')) }}
  ${{ else }}:
    IS_RELEASE: 'false'

steps:

- checkout: self
  persistCredentials: 'true'
  clean: 'true'

- task: Cache@2
  displayName: Cache Maven local repo
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Download Eclipse Temurin
      wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz --output-document $(Agent.TempDirectory)/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: '$(Agent.TempDirectory)/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz'
    jdkDestinationDirectory: '$(Agent.ToolsDirectory)/binaries/openjdk'
    cleanDestinationDirectory: true
    createExtractDirectory: false

- task: Maven@3
  displayName: Set project version to ${{ parameters.RELEASE_VERSION }}
  condition: and(succeeded(), eq(${{ variables.IS_RELEASE }}, 'true'))
  inputs:
    jdkVersionOption: ${{ variables.JDK_VERSION }}
    goals: $(MAVEN_COMMAND_LINE_ARGUMENTS) versions:set -DnewVersion=${{ parameters.RELEASE_VERSION }}
    publishJUnitResults: false


- task: Maven@3
  displayName: Build and test
  inputs:
    jdkVersionOption: ${{ variables.JDK_VERSION }}
    mavenOptions: $(MAVEN_OPTIONS)
    goals: '$(MAVEN_COMMAND_LINE_ARGUMENTS) verify'

- script: |
    git add pom.xml
    git commit -m "[CI] Set version to ${{ parameters.RELEASE_VERSION }}"
    git tag ${{ parameters.RELEASE_VERSION }}
    git push --atomic origin ${{ variables.RELEASE_BRANCH }} ${{ parameters.RELEASE_VERSION }}
  displayName: Commit release version and create release tag
  condition: and(succeeded(), eq(${{ variables.IS_RELEASE }}, 'true'))

  # TODO: Deploy

- task: Maven@3
  displayName: Set project version to ${{ parameters.NEXT_SNAPSHOT_VERSION }}
  condition: and(succeeded(), eq(${{ variables.IS_RELEASE }}, 'true'))
  inputs:
    jdkVersionOption: ${{ variables.JDK_VERSION }}
    goals: '$(MAVEN_COMMAND_LINE_ARGUMENTS) versions:set -DnewVersion=${{ parameters.NEXT_SNAPSHOT_VERSION }}'
    publishJUnitResults: false

- script: |
    git add pom.xml
    git commit -m "[CI] Set version to ${{ parameters.RELEASE_VERSION }}"
    git push
  displayName: Commit next snapshot version
  condition: and(succeeded(), eq(${{ variables.IS_RELEASE }}, 'true'))
